### ** Python : Handling Missing Values in datasets. ** ###

##### let us walk through some python pandas data cleaning techniques to locate and manage missing values in our dataset : *'data_set.csv'* #####

In [103]:
import pandas as pd
import numpy as np

In [105]:
df = pd.read_csv('data/data_set.csv')
df.head()

  AgentID Desk_Number      Street_Name CustID  Num_Calls Language  Call_result
0  020001        D501    Ooivaarstraat  Cu381          9       Fr     Approval
1     NaN        D806  GabpetitStraatt  Cu201         12       Fr  appointment
2  020017        D059     elyseestraat    NaN          9       Fr       Denial
3  020101        D124       Lovendegem  Cu415         23       Nl     Approval
4  020345        D237   Martelaarslaan  Cu011          7       Fr      Refusal

In [106]:
df

,AgentID,Desk_Number,Street_Name,CustID,Num_Calls,Language,Call_result
0,020001,D501,Ooivaarstraat,Cu381,9,Fr,Approval
1,NaN,D806,GabpetitStraatt,Cu201,12,Fr,appointment
2,020017,D059,elyseestraat,NaN,9,Fr,Denial
3,020101,D124,Lovendegem,Cu415,23,Nl,Approval
4,020345,D237,Martelaarslaan,Cu011,7,Fr,Refusal
5,020090,D611,NaN,Cu026,20,Nl,Refusal
6,020000,D406,Roi baudoin,Cu0102,51,Nl,NaN
7,020420,D341,Rue Laure,Cu011,77,Fr,Refusal
8,NaN,D501,Rue bafou,Cu264,102,NaN,Refusal
9,020111,D222,atomiumstraat,na,6,Fr,Refusal
10,?,D501,NaN,Cu021,42,Fr,Refusal
11,020888,D501,eiprestraat,Cu017,5,Fr,Approval
12,020231,??,--,Cu091,4,Fr,Refusal
13,020909,D501,Martelaarslaan,Cu331,51,Nl,Approval
14,020660,D501,---,Cu490,38,Fr,Refusal
15,020199,D501,Martelaarslaan,NaN,18,Fr,Refusal
16,NaN,NaN,zaventemStraat,NaN,1,Fr,#

In [100]:
df['Street_Name']

0       Ooivaarstraat
1     GabpetitStraatt
2        elyseestraat
3          Lovendegem
4      Martelaarslaan
5                 NaN
6         Roi baudoin
7           Rue Laure
8           Rue bafou
9       atomiumstraat
10                NaN
11        eiprestraat
12                 --
13     Martelaarslaan
14                ---
15     Martelaarslaan
16     zaventemStraat
Name: Street_Name, dtype: object

In [101]:
df['Street_Name'].isnull()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16    False
Name: Street_Name, dtype: bool

# Note on above:: pandas only recognizes values in 5/ and 10/ as null or missing; though values in 12/ and 14/ are equally missing.

In [133]:
# Null values in data_set.csv as for pandas.
df_isnull_check = df.isnull()
df_isnull_check

,AgentID,Desk_Number,Street_Name,CustID,Num_Calls,Language,Call_result
0,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False
2,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False
6,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False
8,True,False,False,False,False,True,False
9,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,True,False,False,False
16,True,True,False,True,False,False,False

* Note on above:: As previously noticed in feature 'Street_Name', the whole dataset has more missing values that are not recognized by pandas.

In [127]:
def cell_highlight(val):
    color = 'orangered' if val == 'True'  else 'green'
    return 'color: {color}.'

In [132]:
df_isnull_check.style.applymap(cell_highlight)